### ISSUE TITLE
Load JSON into Python

### ISSUE THREAD

**Issue by bbaum5** [freddie316/ME-EN-6250-Project#14]
We need to load the information saved to our JSON files into a dictionary or pandas DataFrame. bokehLinkedInputs.py provides a possible structure for the dictionary/DataFrame.

The way we will get data looks like this:
1. countryScrape in python and send that to a JSON file
2. Read in the JSON file to our Dashboard.py.
3. Use Dashboard.py to turn the JSON information into a DataSource so this can be used and updated by Javascript.

This issue is related specifically to step 2.

**Comment by freddie316** [comment]
Is line 70 in the current ScrapeWebsite.py what you're looking for?
dfPrev = pd.read_json(output)
reads a json file where output is the filepath to it, and gets the data frame stored within

**Comment by bbaum5** [comment]
I can't run it right now, but it looks like that's exactly what we need.
I guess to add to that we just need a nice way of getting that for every country in Dashboard.py. Ideally, I would like to have a single dataframe showing information for every country. This would help a lot with the JavaScript code.

**Comment by bbaum5** [comment]
If we do get all the information into one dataframe I believe we can also bypass the need to write country-list.txt and continent-list.txt because the dropdown options can be generated directly from that dataframe.
